#!/bin/sh

username=$(who am i | awk '{print $1}')
ckpath="/Users/$username/.ck"
readonly fernflower_source="$ckpath/fernflower.jar"
source_filename="$1"
clean_filename=$(echo "$source_filename" | rev | sed -e "s/^.*\.//1" | rev)

echo "[kj] Compiling $source_filename ..."
kotlinc "$1".kt -nowarn

compiled_filename=$(ls -lt | sed -n 2p | awk '{ print $9 }')

echo '[kj] Decompiling to Java ...'
java -jar "$ckpath"/fernflower.jar "$compiled_filename" .
decompiled_filename=$(ls -lt | sed -n 2p | awk '{ print $9 }')
mv "$decompiled_filename" "$clean_filename".java

rm "$compiled_filename"

echo '[kj] Finished.'
